version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask_app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask.rule=Host(`flask.transformetech.com`)"
      - "traefik.http.routers.flask.entrypoints=web"
      - "traefik.http.services.flask.loadbalancer.server.port=5000"
    networks:
      - traefik
    restart: always

networks:
  traefik:
    external: true
